version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: UserService
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: abc
    ports:
      - "5432:5432"
    networks:
      - app-network

  user-service:
    image: user-service:latest
    container_name: user-service
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/UserService
      SPRING_DATASOURCE_USERNAME: abc
      SPRING_DATASOURCE_PASSWORD: abc
      JWT_SECRET: your-very-secure-256-bit-secret-key-here
      JWT_EXPIRATION: 3600
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
